version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true

formats: all

build:
  image: latest

python:
   version: 3.8
   install:
      - requirements: docs/rtd-pip-requirements.txt
      - method: pip
        path: .
        extra_requirements:
            - docs
      - method: setuptools
        path: .
   system_packages: false

submodules:
   include: all
